server.port=8093
spring.application.name=calling
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.rhynvergxcgxfpcakenn
spring.datasource.password=BOCUQN7Vtoxbwpk4
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect