spring.application.name=gateway
server.port=9000

#spring.docker.compose.enabled=false

server.forward-headers-strategy=framework
# Change this when in prod
jwt.secret=2502db48edbfbe54b02d318f50e4e4cb
jwt.expiration=12345678

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.messaging=DEBUG
logging.level.org.springframework.cloud.gateway.server.mvc=DEBUG
logging.level.org.springframework.web.servlet.function=DEBUG
logging.level.org.springframework.web.client.RestClient=TRACE

services.auth-url=${SERVICES_AUTH_URL:http://localhost:8090}
services.friends-url=${SERVICES_FRIENDS_URL:http://localhost:8092}