spring.application.name=gateway

server.port=9000

services.auth-url=http://localhost:8090
services.messaging-url=http://localhost:8091
services.friends-url=http://localhost:8092

spring.docker.compose.enabled=false

jwt.secret=2502db48edbfbe54b02d318f50e4e4cb
jwt.expiration=12345678