spring.application.name=user-login
server.port=8090

spring.datasource.url=jdbc:postgresql://localhost:5433/users
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.docker.compose.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

# SUPABASE CONN STRING

#spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres
#spring.datasource.username=postgres.rhynvergxcgxfpcakenn
#spring.datasource.password=BOCUQN7Vtoxbwpk4
