spring.application.name=auth
server.port=8090

#spring.datasource.url=jdbc:postgresql://localhost:5433/users
#spring.datasource.username=admin
#spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.docker.compose.enabled=false

jwt.secret=2502db48edbfbe54b02d318f50e4e4cb
jwt.expiration=12345678

spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.rhynvergxcgxfpcakenn
spring.datasource.password=BOCUQN7Vtoxbwpk4

logging.level.org.springframework.security=DEBUG