spring.application.name=messaging
server.port=8091

spring.datasource.url=jdbc:postgresql://postgres-messages:5432/messages
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework.messaging=TRACE
logging.level.org.springframework.web.socket=TRACE
logging.level.org.springframework.web.socket.messaging=TRACE
