spring.application.name=messaging
server.port=8091

spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?prepareThreshold=0
spring.datasource.username=postgres.rhynvergxcgxfpcakenn
spring.datasource.password=BOCUQN7Vtoxbwpk4
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=3

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.docker.compose.enabled=false

logging.level.org.springframework.messaging=DEBUG
logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.web.socket.messaging=DEBUG
logging.level.capstone.server.messaging.service=INFO

jwt.secret=2502db48edbfbe54b02d318f50e4e4cb
jwt.expiration=12345678